language: rust
sudo: false

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - gcc-multilib

jobs:
    include:
        - env: ARCH=x86_64
          rust: 1.21.0
          os: linux
        - env: ARCH=i686
          rust: 1.21.0
          os: linux
        - env: ARCH=x86_64
          rust: 1.21.0
          os: osx
        - env: ARCH=i686
          rust: 1.21.0
          os: osx
        - env: ARCH=x86_64
          rust: 1.19.0
          os: linux
        - env: ARCH=i686
          rust: 1.19.0
          os: linux
        - env: ARCH=x86_64
          rust: 1.14.0
          os: linux
        - env: ARCH=i686
          rust: 1.14.0
          os: linux
        - env: ARCH=x86_64
          rust: nightly
          os: linux
        - env: ARCH=i686
          rust: nightly
          os: linux
        - env: ARCH=x86_64
          rust: beta
          os: linux
        - env: ARCH=i686
          rust: beta
          os: linux

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - export HOST=$ARCH-$OS
    - if [ $ARCH = 'i686' ]; then rustup target add $HOST; fi

script:
    - cargo test --no-default-features --target "$HOST"
    - cargo test --target "$HOST"

after_success:
    - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
    - cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | bash
    - cargo kcov --target "$HOST" --coveralls

